### ISSUE TITLE
Super awesome

### ISSUE THREAD

**Issue by matteofigus** [daiyip/continuous-modification#1]
Hey @daiyip, not sure this is the right place to do this, but I really wanted to thank you for this writing.

At Opentable we have been working on similar concepts now for a couple of years in a project called [OpenComponents](https://github.com/opentable/oc) and this really changed our perspective on so many things.

I would love to learn more about your experience and real application of these principles. Are issues in this repo good for discussing? Is this something you are ok with?

**Comment by daiyip** [comment]
@matteofigus, thanks for your kind words.

It's great to learn that this post is helpful in any regard, you can email me if you have any questions.
